---
wordpress_version: "6.8.3"
wordpress_url: "https://wordpress.org/wordpress-{{ wordpress_version }}.zip"
db_root_password: "{{ vault_db_root_password }}"
db_name: "wordpress"
db_user: "wordpress"
db_password: "{{ vault_db_password }}"
wp_admin_user: "admin"
wp_admin_password: "{{ vault_wp_admin_password }}"
wp_admin_email: admin@example.com
wordpress_db_host: 192.168.11.20
packages_webserver:
  - apache2
  - php
  - libapache2-mod-php
  - php-mysql
  - unzip
  - wget
  - php
  - php-cli
  - php-fpm
  - php-mysql
  - php-xml
  - php-curl
  - php-mbstring
  - php-zip
packages_database:
  - mysql-server
  - python3-pip
  - python3-pymysql
packager_loadbalancer:
  - nginx